URL = "https://stellarburgers.nomoreparties.site/"
EMAIL = "DmitriyOdintsov_08_196@yandex.ru"
PASSWORD = "Dima08"
NAME = "Дмитрий"
LOGIN_WINDOW_URL = "https://stellarburgers.nomoreparties.site/login"
